// Extra 169 glossary terms - loaded after script.js
const extraGlossary = [
{term:"A/B Testing (AI)",def:"השוואת שתי גרסאות של מודל או prompt כדי לראות מי עובד טוב יותר"},
{term:"Accuracy",def:"דיוק - אחוז התחזיות הנכונות מסך כל התחזיות"},
{term:"Active Learning",def:"המודל בוחר אילו דוגמאות הכי כדאי לתייג - חוסך עבודה"},
{term:"Adapter",def:"מודול קטן שנוסף למודל קיים לצורך התאמה - חלופה ל-fine-tuning מלא"},
{term:"AI Alignment",def:"התאמת מטרות AI למטרות אנושיות - הבטחה ש-AI עושה מה שאנחנו רוצים"},
{term:"AI Winter",def:"תקופות שבהן המימון והעניין ב-AI ירדו (שנות ה-70 וה-80)"},
{term:"Annotation",def:"תיוג ידני של נתונים - תהליך יקר אבל חיוני לאימון מודלים"},
{term:"API Rate Limit",def:"מגבלת קריאות ל-API - כמה בקשות מותר לשלוח בדקה"},
{term:"Artificial Neuron",def:"יחידת חישוב בסיסית ברשת - מקבלת קלטים, מכפילה במשקלות"},
{term:"Autoencoder",def:"רשת שלומדת לדחוס נתונים ולשחזר אותם - שימושית לזיהוי אנומליות"},
{term:"Autoregressive",def:"מודל שמייצר פלט טוקן-אחר-טוקן, כל אחד מושפע מהקודמים (GPT)"},
{term:"Batch Normalization",def:"נרמול ערכים על פני ה-batch - מייצב אימון רשתות עמוקות"},
{term:"Beam Search",def:"שיטת פענוח שבודקת מספר מסלולים במקביל - תשובות טובות יותר"},
{term:"BLEU Score",def:"מדד אוטומטי לאיכות תרגום מכונה - משווה למתרגם אנושי"},
{term:"Causal Language Model",def:"מודל שפה שמנבא רק קדימה (שמאל לימין) - GPT הוא דוגמה"},
{term:"Checkpoint",def:"שמירת מצב המודל באמצע אימון - מאפשר המשך מנקודה מסוימת"},
{term:"CLIP",def:"מודל OpenAI שמקשר טקסט לתמונות - הבסיס של DALL-E"},
{term:"Codex",def:"מוצר OpenAI ל-coding agents - מריץ קוד בסביבה מבודדת"},
{term:"Confidence Score",def:"ציון ביטחון - כמה המודל בטוח בתשובתו (0-100%)"},
{term:"Contrastive Learning",def:"למידה ע\"י השוואת זוגות דומים ושונים - בסיס ל-CLIP"},
{term:"Conversational AI",def:"AI שמנהל שיחות טבעיות - צ'אטבוטים ועוזרים"},
{term:"CUDA Cores",def:"ליבות חישוב מקביליות ב-GPU של NVIDIA"},
{term:"Curriculum Learning",def:"אימון הדרגתי - מתחילים עם דוגמאות קלות ומתקדמים"},
{term:"Data Drift",def:"שינוי בהתפלגות הנתונים לאורך זמן - גורם לירידת ביצועים"},
{term:"Data Lake",def:"מאגר נתונים ענק שמאחסן הכל בצורה גולמית"},
{term:"Data Pipeline",def:"צינור נתונים אוטומטי - איסוף, ניקוי, והזנה למודל"},
{term:"Decision Boundary",def:"הגבול שהמודל לומד בין קטגוריות שונות"},
{term:"Decoder",def:"החלק ברשת שמייצר פלט - מתרגם ייצוג פנימי לטקסט/תמונה"},
{term:"DeepSeek",def:"חברת AI סינית - מודלים תחרותיים בעלויות נמוכות (V4, DSpark)"},
{term:"Dense Model",def:"מודל שמפעיל את כל הפרמטרים לכל קלט - בניגוד ל-MoE"},
{term:"Deterministic",def:"מודל שנותן תמיד אותה תשובה לאותו קלט (Temperature=0)"},
{term:"DPO",def:"Direct Preference Optimization - אימון לפי העדפות בלי Reward Model"},
{term:"DSpark",def:"framework של DeepSeek (יוני 2026) להאצת inference ב-85%"},
{term:"Early Stopping",def:"עצירת אימון כשהביצועים מפסיקים להשתפר - מונע overfitting"},
{term:"ELO Rating (AI)",def:"דירוג מודלים ע\"י השוואות זוגיות - כמו שחמט"},
{term:"Emergent Abilities",def:"יכולות שמופיעות רק במודלים גדולים - reasoning, humor"},
{term:"Encoder",def:"החלק שמקודד קלט לייצוג פנימי - מבין את המשמעות"},
{term:"Entity Extraction",def:"חילוץ ישויות מטקסט - שמות, תאריכים, מיקומים"},
{term:"F1 Score",def:"ממוצע הרמוני של Precision ו-Recall - מדד מאוזן"},
{term:"FAISS",def:"ספריית Meta לחיפוש similarity מהיר - בסיס ל-vector search"},
{term:"Feature Engineering",def:"יצירת features חדשים מנתונים גולמיים - אומנות ב-ML"},
{term:"Feature Store",def:"מערכת לאחסון ושיתוף features מחושבים בין צוותים"},
{term:"Flash Attention",def:"אלגוריתם attention יעיל שחוסך זיכרון GPU - סטנדרט 2026"},
{term:"FLOPS",def:"Floating Point Operations Per Second - מדד לכוח חישוב"},
{term:"Frozen Layers",def:"שכבות שלא מתעדכנות ב-fine-tuning - חוסך חישוב"},
{term:"Generalization",def:"יכולת מודל לעבוד טוב על נתונים שלא ראה באימון"},
{term:"Generative Model",def:"מודל שיוצר תוכן חדש - בניגוד ל-discriminative שרק מסווג"},
{term:"GNN",def:"Graph Neural Network - רשת שעובדת על גרפים"},
{term:"GPT-5.6 Sol",def:"הדגל של OpenAI (יוני 2026) - $5/$30, מוגבל ל-20 שותפים"},
{term:"GPT-5.6 Terra",def:"מודל מאוזן - ביצועי GPT-5.5 בחצי מחיר ($2.50/$15)"},
{term:"GPT-5.6 Luna",def:"מהיר וזול - $1/$6, לעבודות בנפח גבוה"},
{term:"Grok 4.5",def:"מודל xAI (יוני 2026) - 1.5T params, בטא פרטית Tesla/SpaceX"},
{term:"Ground Truth",def:"התשובה הנכונה האמיתית - לבדיקת ביצועי המודל"},
{term:"Groq LPU",def:"שבב חומרה ייעודי ל-inference מהיר במיוחד"},
{term:"Head (Model)",def:"שכבה אחרונה שמתאימה פלט למשימה ספציפית"},
{term:"Hidden State",def:"הייצוג הפנימי של המידע בתוך הרשת"},
{term:"HumanEval",def:"בנצ'מרק של OpenAI למדידת יכולת כתיבת קוד"},
{term:"Hybrid Search",def:"שילוב חיפוש keyword (BM25) עם חיפוש סמנטי (vectors)"},
{term:"Inductive Bias",def:"ההנחות המובנות בארכיטקטורה - CNN מניח locality"},
{term:"Instruction Tuning",def:"אימון מודל לעקוב אחרי הוראות - מה שיוצר ChatGPT"},
{term:"JSON Mode",def:"מצב שמכריח את המודל להחזיר JSON תקין"},
{term:"KV Cache",def:"שמירת חישובי Key-Value מ-attention - מאיץ inference"},
{term:"LangGraph",def:"ספרייה לבניית agent workflows כגרפים"},
{term:"LangSmith",def:"פלטפורמת ניטור לאפליקציות LLM - של LangChain"},
{term:"Latent Space",def:"מרחב נסתר - הייצוג הדחוס שמודל לומד"},
{term:"Layer",def:"שכבה ברשת נוירונים - כל שכבה מבצעת טרנספורמציה"},
{term:"LLaMA",def:"משפחת מודלים פתוחים של Meta - LLaMA 4 עדכני"},
{term:"Logits",def:"ציוני הגלם לפני softmax - העדפה לכל טוקן"},
{term:"Long Context",def:"יכולת לעבד טקסטים ארוכים - Gemini 3.5: 2M tokens"},
{term:"MAE",def:"Mean Absolute Error - ממוצע השגיאה המוחלטת, מדד לרגרסיה"},
{term:"Masked Language Model",def:"מודל שלומד לנחש מילים חסרות (BERT)"},
{term:"Memory (Agent)",def:"יכולת agent לזכור מידע מאינטראקציות קודמות"},
{term:"Meta-Learning",def:"למידה ללמוד - מודל שמסתגל מהר למשימות חדשות"},
{term:"Mistral",def:"חברת AI צרפתית - מודלים קטנים ויעילים, Mixtral MoE"},
{term:"Model Card",def:"מסמך שמתאר מודל - יכולות, מגבלות, הטיות"},
{term:"Model Merging",def:"שילוב משקלות של מודלים שונים ליצירת מודל חדש - ללא אימון"},
{term:"Model Pruning",def:"הסרת חלקים מיותרים מהמודל להקטנת גודל"},
{term:"Model Registry",def:"מערכת לניהול גרסאות מודלים - כמו Git למודלים"},
{term:"Multi-Head Attention",def:"מספר מנגנוני attention במקביל - כל head לומד דפוס אחר"},
{term:"Multi-Turn",def:"שיחה עם כמה תורות הלוך-חזור"},
{term:"NER",def:"Named Entity Recognition - זיהוי ישויות בטקסט"},
{term:"Next Token Prediction",def:"המשימה הבסיסית של GPT - חיזוי המילה הבאה"},
{term:"NVIDIA H100",def:"ה-GPU המוביל לאימון AI - $25K-40K, סטנדרט התעשייה"},
{term:"NVIDIA Blackwell",def:"דור ה-GPU הבא (B200) - קפיצת ביצועים"},
{term:"One-Hot Encoding",def:"ייצוג קטגוריות כוקטור בינארי - [0,1,0,0]"},
{term:"OpenAI",def:"חברת AI - GPT, ChatGPT, DALL-E, Sora. CEO: Sam Altman"},
{term:"Optimizer",def:"אלגוריתם שמעדכן משקלות באימון - Adam הנפוץ ביותר"},
{term:"Output Token",def:"טוקן שהמודל מייצר - עולה יותר מ-input token"},
{term:"Padding",def:"הוספת טוקנים ריקים להשלמת אורך קבוע"},
{term:"Perplexity (Metric)",def:"מדד שמעריך כמה המודל מופתע - נמוך = טוב"},
{term:"Perplexity AI",def:"מנוע חיפוש AI עם מקורות - מתחרה ב-Google"},
{term:"Pipeline (ML)",def:"שרשרת שלבים אוטומטית מנתונים עד תחזית"},
{term:"Precision",def:"מתוך מה שזיהינו כחיובי - כמה באמת חיובי"},
{term:"Project Glasswing",def:"תוכנית ממשלת ארה\"ב לגישה מבוקרת למודלי frontier"},
{term:"Prompt Caching",def:"שמירת עיבוד System Prompt - חוסך עלות בקריאות חוזרות"},
{term:"QLoRA",def:"Quantization + LoRA - fine-tuning מודלים גדולים על GPU בודד"},
{term:"Random Forest",def:"אנסמבל של עצי החלטה - אלגוריתם ML קלאסי ויעיל"},
{term:"Recall",def:"מתוך כל החיוביים האמיתיים - כמה הצלחנו למצוא"},
{term:"RNN",def:"Recurrent Neural Network - עיבוד רצפי. הוחלפה ע\"י Transformers"},
{term:"Regularization",def:"טכניקות למניעת overfitting - Dropout, Weight Decay"},
{term:"Retriever",def:"רכיב שמחפש מידע רלוונטי ממאגר - חלק מרכזי ב-RAG"},
{term:"RoPE",def:"Rotary Position Embedding - קידוד מיקום מודרני ב-LLaMA, Mistral"},
{term:"ROUGE",def:"מדד לאיכות סיכום טקסט - משווה לסיכום אנושי"},
{term:"Safety Filter",def:"מסנן שמונע תוכן מסוכן לפני שליחה למשתמש"},
{term:"Semantic Similarity",def:"מדידת דמיון במשמעות בין שני טקסטים"},
{term:"Sentiment Analysis",def:"ניתוח רגשות - חיובי, שלילי או ניטרלי"},
{term:"SHAP",def:"שיטה להסבר תחזיות - מראה מה השפיע על כל החלטה"},
{term:"Sigmoid",def:"פונקציית activation שדוחסת ערכים לטווח 0-1"},
{term:"SLM",def:"Small Language Model (1-7B) - מהיר, זול, רץ מקומית (Phi, Gemma)"},
{term:"Softmax",def:"פונקציה שממירה ציונים להסתברויות (סכום = 1)"},
{term:"Sora",def:"מודל וידאו OpenAI - סרטונים ריאליסטיים מטקסט"},
{term:"Speculative Decoding",def:"מודל קטן מנחש, גדול מאשר - מאיץ inference (DSpark)"},
{term:"Stable Diffusion",def:"מודל קוד פתוח ליצירת תמונות - רץ מקומית"},
{term:"Stop Sequence",def:"טוקן שאומר למודל להפסיק לייצר"},
{term:"Streaming (API)",def:"קבלת תשובה טוקן-אחר-טוקן בזמן אמת"},
{term:"Suno AI",def:"פלטפורמה ליצירת שירים מלאים - מילים ומוזיקה מטקסט"},
{term:"SWE-Bench",def:"בנצ'מרק למדידת יכולת AI לפתור באגים אמיתיים מ-GitHub"},
{term:"T5",def:"Text-to-Text Transfer Transformer - מודל Google לכל משימת טקסט"},
{term:"Tensor",def:"מערך רב-ממדי של מספרים - מבנה הנתונים הבסיסי ב-DL"},
{term:"TensorFlow",def:"ספריית deep learning של Google"},
{term:"Text-to-Image",def:"יצירת תמונה מטקסט - DALL-E, Midjourney, SD"},
{term:"Text-to-Speech",def:"המרת טקסט לדיבור טבעי - ElevenLabs, OpenAI TTS"},
{term:"Tokenizer",def:"אלגוריתם שמפרק טקסט לטוקנים - BPE, WordPiece"},
{term:"Top-k Sampling",def:"בחירה רק מתוך k הטוקנים הסבירים ביותר"},
{term:"Top-p Sampling",def:"בחירה מטוקנים שביחד מהווים p% מההסתברות"},
{term:"PyTorch",def:"ספריית deep learning הפופולרית ביותר (Meta)"},
{term:"Turing Test",def:"האם מכונה יכולה להתחזות לאדם בשיחה?"},
{term:"Underfitting",def:"מודל פשוט מדי שלא לומד - ההפך מ-overfitting"},
{term:"Validation Set",def:"נתונים לבדיקת ביצועים תוך כדי אימון"},
{term:"VLM",def:"Vision-Language Model - מבין טקסט וגם תמונות (GPT-4V, Claude)"},
{term:"Warmup",def:"התחלה עם learning rate נמוך שעולה בהדרגה"},
{term:"Whisper",def:"מודל OpenAI לתמלול דיבור - 99 שפות, קוד פתוח"},
{term:"Word2Vec",def:"שיטה מ-2013 להמרת מילים לוקטורים - king-man+woman=queen"},
{term:"XGBoost",def:"אלגוריתם ML קלאסי - הטוב ביותר לנתונים טבלאיים"},
{term:"YOLO",def:"You Only Look Once - זיהוי אובייקטים בזמן אמת"},
{term:"Claude Fable 5",def:"Anthropic (יוני 2026) - Mythos-class ציבורי, $10/$50, 80% SWE-Bench"},
{term:"Anthropic",def:"חברת AI שפיתחה Claude. מייסדים: Dario & Daniela Amodei. IPO $1T+ ב-2026"},
{term:"Sam Altman",def:"מנכ\"ל OpenAI - הפנים של מהפכת ה-AI הנוכחית"},
{term:"Jensen Huang",def:"מנכ\"ל NVIDIA - ה-arms dealer של מירוץ ה-AI"},
{term:"Demis Hassabis",def:"מנכ\"ל Google DeepMind - AlphaGo, AlphaFold, נובל 2024"},
{term:"Geoffrey Hinton",def:"אבי Deep Learning - נובל 2024, הזהיר מסכנות AI"},
{term:"Yann LeCun",def:"Chief AI Scientist ב-Meta - CNN, קוד פתוח"},
{term:"Ilya Sutskever",def:"מייסד SSI, לשעבר Chief Scientist OpenAI"},
{term:"ImageNet",def:"מאגר תמונות ותחרות שהניעה את מהפכת Deep Learning (2012)"},
{term:"AlphaGo",def:"מודל DeepMind שניצח אלוף העולם בגו (2016) - רגע מכונן ב-AI"},
{term:"Chinchilla Laws",def:"חוקי scaling של DeepMind - כמה דאטה צריך ביחס לגודל המודל"},
{term:"Mixture of Agents",def:"שילוב תשובות ממספר מודלים שונים לתוצאה טובה יותר"},
{term:"Routing (AI)",def:"שליחת שאילתות קלות למודל זול וקשות למודל יקר - חוסך כסף"},
{term:"Agentic Workflow",def:"זרימת עבודה שבה agent מתכנן ומבצע צעדים אוטונומית"},
{term:"Code Interpreter",def:"סביבה שמאפשרת ל-AI להריץ קוד ולראות תוצאות"},
{term:"Computer Use",def:"יכולת AI לשלוט במחשב - קליקים, הקלדה, ניווט"},
{term:"Context Stuffing",def:"דחיסת מידע רב ככל האפשר לתוך חלון ההקשר"},
{term:"Document AI",def:"עיבוד מסמכים אוטומטי - OCR, חילוץ נתונים, סיכום"},
{term:"Eval (AI)",def:"תהליך הערכת ביצועי מודל - בנצ'מרקים, בדיקות אנושיות"},
{term:"Gemini",def:"משפחת מודלי AI של Google DeepMind - מולטי-מודאלי, חלון ענק"},
{term:"Inference Cost",def:"עלות הרצת מודל על שאילתה בודדת - נמדד ב-$/M tokens"},
{term:"Knowledge Distillation",def:"העברת ידע ממודל גדול (teacher) לקטן (student)"},
{term:"Llama Guard",def:"מודל בטיחות של Meta שמסנן תוכן מסוכן"},
{term:"MAI-Code-1-Flash",def:"מודל קידוד של Microsoft (יוני 2026) - ב-GitHub Copilot"},
{term:"Model Serving",def:"תשתית להרצת מודלים בפרודקשן - APIs, load balancing"},
{term:"NVIDIA NIM",def:"פלטפורמת NVIDIA לפריסת מודלים מותאמים - containers מוכנים"},
{term:"Pinecone",def:"מסד נתונים וקטורי מנוהל בענן - פופולרי ל-RAG"},
{term:"Prompt Chaining",def:"שרשור כמה prompts - הפלט של אחד הופך לקלט של הבא"},
{term:"Reward Hacking",def:"כשמודל מוצא דרך לקבל ציון גבוה בלי באמת לפתור את המשימה"},
{term:"Tokenomics (AI)",def:"כלכלת הטוקנים - מחיר input vs output, batch discounts"},
{term:"Weights & Biases",def:"פלטפורמה לניטור ניסויי ML - logging, visualization"},
{term:"Window Attention",def:"attention מוגבל לחלון מקומי - חוסך חישוב בטקסטים ארוכים"},
{term:"AI Native",def:"אפליקציה שנבנתה מהיסוד סביב AI - לא AI כתוספת (Kiro, Cursor)"}
];

// Merge with existing glossaryData
if (typeof glossaryData !== 'undefined') {
    glossaryData.push(...extraGlossary);
    // Re-render glossary if function exists
    if (typeof renderGlossary === 'function') {
        const glossaryList = document.getElementById('glossaryList');
        if (glossaryList) renderGlossary(glossaryData);
    }
}
